config/routes.rb
Rails.application.routes.draw do
  get '/hello', to: 'static_pages#hello'
  get '/about', to: 'static_pages#about'
  get '/sign_up', to: 'users#new'
  post '/sign_up', to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  root 'static_pages#hello'
  
  
  resources :users do
    member do
      get :favorites
      get :following_users
      get :followers
      post :follow, to: 'relationships#create'
      delete :unfollow, to: 'relationships#destroy'
    end
  end
  
  resources :books do
    resource :favorite, :only => [:create, :destroy]
    resource :review, :only => [:create, :destroy]
  end
  
end

app/models/user.rb
class User < ApplicationRecord
    has_many :books
    has_many :favorites
    has_many :favorite_books, through: :favorites, source: :book
    
    has_many :reviews
    
    has_many :following, class_name: "Relationship", foreign_key: "follower_id"
    has_many :following_users, through: :following, source: :followed
    
    has_many :being_followed, class_name: "Relationship", foreign_key: "followed_id"
    has_many :followers, through: :being_followed, source: :follower
    
    def follow(user_id)
      following.create!(followed_id: user_id)
    end
    
    def unfollow(user_id)
      following.find_by(followed_id: user_id).destroy!
    end
    
    validates :name, presence: true, length: { maximum: 50 }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, length: { maximum: 200 }, uniqueness: true
    has_secure_password
    validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]
  include SessionsHelper
  
  def index
    @users = User.all.page(params[:page]).per(10)
  end
  
  def new
    @user = User.new
  end
  
  def show
    @user = User.find_by(id: params[:id])
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = '登録に成功しました'
      redirect_to @user
    else
      flash.now[:danger] = '登録に失敗しました'
      render "new"
    end
  end
  
  def edit
  end
  
  def update
    @user.assign_attributes(user_params)
    if @user.save
      flash[:success] = '更新に成功しました'
      redirect_to @user
    else
      flash.now[:danger] = '更新に失敗しました'
      render "edit"
    end
  end
  
  def destroy
    User.find_by(id: params[:id]).destroy!
    redirect_to users_url
  end
  
  def favorites
    @books = User.find_by(id: params[:id]).favorite_books
  end
  
  def following_users
    @users = User.find_by(id: params[:id]).following_users
  end
  
  def followers
    @users = User.find_by(id: params[:id]).followers
  end
  
  
  private
  
  def logged_in_user
    unless logged_in?
      store_url
      flash[:danger] = "ログインしてください"
      redirect_to login_url
    end
  end
  
  def correct_user
    @user = User.find_by(id: params[:id])
    if current_user != @user
      flash[:danger] = '他人のユーザー情報を編集することはできません'
      redirect_to root_url
    end
  end  
  
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_user.html.erb
<p><%= user.name %></p>
<p><%= user.email %></p>

app/views/users/edit.html.erb
<%= render 'shared/object_error_messages', object: @user %>
<div class="top">
  <p> ユーザー更新ページ</p>
</div>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_with(model: @user, local: true) do |f| %>
      <%= f.label :name, "氏名" %>
      <%= f.text_field :name %>
      
      <%= f.label :email %>
      <%= f.email_field :email %>

      <%= f.label :password, "パスワード" %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "パスワード（確認）" %>
      <%= f.password_field :password_confirmation %>
      
      <%= f.submit "アカウント更新", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/favorites.html.erb
<div class="top">
  <p>いいねした本一覧ページ</p>
  <% @books.each do |book| %>
    <%= render book %>
      <p><%= link_to "この本の詳細を見る", book %></p>
      <br>
  <% end %>
</div>

app/views/users/followers.erb
<div class="top">
  <p>フォロワー一覧ページ</p>
  <% @users.each do |user| %>
    <%= render user %>
      <p><%= link_to "このユーザーの詳細を見る", user %></p>
      <br>
  <% end %>
</div>

app/views/users/following_users.html.erb
<div class="top">
  <p>フォローしているユーザー一覧ページ</p>
  <% @users.each do |user| %>
    <%= render user %>
      <p><%= link_to "このユーザーの詳細を見る", user %></p>
      <br>
  <% end %>
</div>

app/views/users/index.html.erb
<div class="top">
  <p>ユーザー一覧ページ</p>
  <%= render @users %>
  <%= paginate @users %>
</div>

app/views/users/new.html.erb
<%= render 'shared/object_error_messages', object: @user %>
<div class="top">
  <p> ユーザー登録ページ</p>
</div>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_with(model: @user, local: true, url: sign_up_path) do |f| %>
      <%= f.label :name, "氏名" %>
      <%= f.text_field :name %>
      
      <%= f.label :email %>
      <%= f.email_field :email %>

      <%= f.label :password, "パスワード" %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "パスワード（確認）" %>
      <%= f.password_field :password_confirmation %>
      
      <%= f.submit "アカウント登録", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="top">
  <p>ユーザー詳細ページ</p>
  <%= render @user %>
  <% if current_user == @user %>
    <p><%= link_to "ユーザー情報を編集", edit_user_path %></p>
  <% elsif Relationship.find_by(follower_id: current_user.id, followed_id: @user.id)  %>
    <p><%= link_to "フォロー解除", unfollow_user_path(@user), method: :delete %></p>
  <% else %>
    <p><%= link_to "フォロー", follow_user_path(@user), method: :post %></p>
  <% end %>
    
  <p><%= link_to "いいねした本", favorites_user_path %></p>
  
  <p><%= link_to "フォローしているユーザー", following_users_user_path %></p>
  <p><%= link_to "フォロワー", followers_user_path %></p>
  
  <p><%= link_to "削除", @user, method: :delete, data: { confirm: "削除していいですか？"} %></p>
</div>