config/routes.rb
Rails.application.routes.draw do
  get '/hello', to: 'static_pages#hello'
  get '/about', to: 'static_pages#about'
  get '/sign_up', to: 'users#new'
  post '/sign_up', to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  root 'static_pages#hello'
  
  
  resources :users do
    member do
      get :favorites
      get :following_users
      get :followers
      post :follow, to: 'relationships#create'
      delete :unfollow, to: 'relationships#destroy'
    end
  end
  
  resources :books do
    resource :favorite, :only => [:create, :destroy]
    resource :review, :only => [:create, :destroy]
  end
  
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :favorites
  has_many :favorite_users, through: :favorites, source: :user
  
  has_many :reviews
  
  def reviewed_by?(user)
    Review.find_by(user_id: user.id, book_id: self.id)
  end
  
  def average_rate
    reviews.average(:rate).round(1)
  end
  
  def average_rate_with_stars
    return "⭐️" * average_rate.round
  end
    
  validates :name, presence: true
  validates :description, presence: true
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :logged_in_user
  before_action :correct_user, only: [:edit, :update, :destroy]
  include SessionsHelper
  
  def index
    @books = current_user.books.page(params[:page]).per(10)
  end

  def new
    @book = current_user.books.build
  end

  def show
    @book = Book.find_by(id: params[:id])
    @review = Review.new
  end

  def create
    @book = current_user.books.build(book_params)
    if @book.save
      flash[:success] = '登録に成功しました'
      redirect_to @book
    else
      flash.now[:danger] = '登録に失敗しました'
      render "new"
    end
  end

  def edit
  end

  def update
    @book.assign_attributes(book_params)
    if @book.save
      flash[:success] = '更新に成功しました'
      redirect_to @book
    else
      flash.now[:danger] = '更新に失敗しました'
      render "edit"
    end
  end

  def destroy
    Book.find_by(id: params[:id]).destroy!
    redirect_to books_url
  end
  
  private
  
  def book_params
    params.require(:book).permit(:name, :description, :summary, :impression)
  end
  
  def logged_in_user
    unless logged_in?
      store_url
      flash[:danger] = 'ログインしてください'
      redirect_to login_url
    end
  end
  
  def correct_user
    @book = Book.find_by(id: params[:id])
    if current_user != @book.user
      flash[:danger] = '他人の本の情報を編集することはできません'
      redirect_to books_url
    end
  end
  
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_book.html.erb
<p>名前：<%= book.name %></p>
<p>説明：<%= book.description %></p>
<p>要点：<%= book.summary %></p>
<p>感想：<%= book.impression %></p>
<p>所有者：<%= book.user.name %></p>

app/views/books/edit.html.erb
<%= render 'shared/object_error_messages', object: @book %>
<div class="top">
  <p> 本更新ページ</p>
</div>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_with(model: @book, local: true) do |f| %>
      <%= f.label :name, "名前" %>
      <%= f.text_field :name %>
      
      <%= f.label :description,"本の説明" %>
      <%= f.text_field :description %>
      
      <%= f.label :summary,"本の要点" %>
      <%= f.text_field :summary %>
      
      <%= f.label :impression,"本の感想" %>
      <%= f.text_field :impression %>
      
      <%= f.submit "本の情報を更新", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/books/index.html.erb
<div class="top">
  <p>本一覧ページ</p>
  <p><%= link_to "本を登録する", new_book_path %></p>
  <% @books.each do |book| %>
    <%= render book %>
      <p><%= link_to "この本の詳細を見る", book %></p>
      <br>
  <% end %>
  <%= paginate @books %>
</div>

app/views/books/new.html.erb
<%= render 'shared/object_error_messages', object: @book %>
<div class="top">
  <p> 本の登録ページ</p>
</div>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_with(model: @book, local: true) do |f| %>
      <%= f.label :name, "名前" %>
      <%= f.text_field :name %>
      
      <%= f.label :description,"本の説明" %>
      <%= f.text_field :description %>
      
      <%= f.submit "本の登録", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/books/show.html.erb
<div class="top">

  <p>本詳細ページ</p>
  <%= render @book %>
  <% if current_user == @book.user %>
    <p><%= link_to "本情報を編集", edit_book_path(@book) %></p>
    <p><%= link_to "削除", @book, method: :delete, data: { confirm: "削除していいですか？"} %></p>
  <% end %>
  
  <% if Favorite.find_by(user_id: current_user.id, book_id: @book.id) %>
    <p><%= link_to "いいね解除", book_favorite_path(@book), method: :delete %></p>
  <% else %>
    <p><%= link_to "いいね", book_favorite_path(@book), method: :post %></p>
  <% end %>
  
  <% unless @book.reviewed_by?(current_user) %>
    <%= form_with url: book_review_path(@book), scope: :review, local: true do |f| %>
      <%= f.label :review, "レビューする" %>
      <%= f.select :rate, [["5", "5"], ["4", "4"], ["3", "3"], ["2", "2"], ["1", "1"]], include_blank: "選択して下さい" %>
      <%= f.text_area :comment %>
      <%= f.submit "レビューを投稿する", class: "btn btn-primary" %>
    <% end %>
  <% end %>

  <p>レビュー一覧</p>
  <% if @book.reviews.present? %>
  
    <p><%= @book.average_rate %> <%= @book.average_rate_with_stars %></p>
    
    <% @book.reviews.each do |review| %>
      <p>投稿者：<%= review.user.name %></p>
      <p>評価：<%= review.rate %></p>
      <% if review.comment.present? %>
        <p>コメント：<%= review.comment %></p>
      <% end %>
      <% if review.user == current_user %>
        <%= link_to "レビューを削除", book_review_path(@book), data: { confirm: "レビューを削除しますか？"}, method: :delete %>
        <br>
      <% end %>
    <% end %>
  <% else %>
    <p>まだレビューがありません</p>
  <% end %>
  
</div>